import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import { corsOptions } from './config/cors.js';
import { authRoutes } from './routes/auth.routes.js';
import { propertyRoutes } from './routes/property.routes.js';
import { leadRoutes } from './routes/lead.routes.js';
import { adminRoutes } from './routes/admin.routes.js';
import { propertyPageRoutes } from './routes/property-page.routes.js';
import { uploadRoutes } from './routes/upload.routes.js';
import { bannerRoutes } from './routes/banner.routes.js';
import { homepageRoutes } from './routes/homepage.routes.js';
import { pageVisitRoutes } from './routes/pageVisit.routes.js';
import { contactRoutes } from './routes/contact.routes.js';
import { plotRoutes } from './routes/plot.routes.js';
import { errorMiddleware, notFoundMiddleware } from './middleware/error.middleware.js';
export const app = express();
app.set('trust proxy', 1);
app.use(helmet());
app.use(cors(corsOptions));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(morgan('dev'));
app.get('/api/health', (_req, res) => {
    res.json({ success: true, message: 'OK' });
});
app.use('/api/auth', authRoutes);
app.use('/api/properties', propertyRoutes);
app.use('/api/leads', leadRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/property-page', propertyPageRoutes);
app.use('/api/uploads', uploadRoutes);
app.use('/api/banners', bannerRoutes);
app.use('/api/homepage', homepageRoutes);
app.use('/api/page-visits', pageVisitRoutes);
app.use('/api/contact-submissions', contactRoutes);
app.use('/api/plots', plotRoutes);
app.use(notFoundMiddleware);
app.use(errorMiddleware);
